'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import { Download, RotateCcw } from 'lucide-react';
import DeceptionGauge from './DeceptionGauge';
import PatternHighlighter from './PatternHighlighter';
import BreakdownPanel from './BreakdownPanel';
import type { AnalysisResult, PatternFlag } from '@/lib/types';

interface ResultsPanelProps {
  result: AnalysisResult;
  originalText: string;
  onReset: () => void;
}

function exportReport(result: AnalysisResult, text: string) {
  const lines = [
    '═══════════════════════════════════════════════',
    '  VERITY — BEHAVIORAL ANALYSIS REPORT',
    `  ${new Date().toLocaleString()}`,
    '═══════════════════════════════════════════════',
    '',
    `DECEPTION SCORE: ${result.deceptionScore}/100`,
    `VERDICT: ${result.verdict.toUpperCase()}`,
    `ANALYSIS CONFIDENCE: ${result.confidence}%`,
    '',
    'ASSESSMENT:',
    result.summary,
    '',
    '───────────────────────────────────────────────',
    'ANALYZED TEXT:',
    `"${text}"`,
    '',
    '───────────────────────────────────────────────',
    'DETECTED PATTERNS:',
    ...result.patterns.map((p) =>
      `  [${p.severity.toUpperCase()}] ${p.type}: "${p.phrase}"\n    → ${p.explanation}`
    ),
    '',
    '───────────────────────────────────────────────',
    'KEY INSIGHTS:',
    ...result.keyInsights.map((i) => `  • ${i}`),
    '',
    '───────────────────────────────────────────────',
    'LINGUISTIC PROFILE:',
    `  Hedging Density:        ${result.linguisticProfile.hedgingDensity}`,
    `  Qualifier Usage:        ${result.linguisticProfile.qualifierUsage}`,
    `  Negation Patterns:      ${result.linguisticProfile.negationPatterns}`,
    `  Temporal Consistency:   ${result.linguisticProfile.temporalConsistency}`,
    `  Emotional Authenticity: ${result.linguisticProfile.emotionalAuthenticity}`,
    '',
    '═══════════════════════════════════════════════',
    '  Generated by VERITY AI Behavioral Analysis',
    '  Note: This is a linguistic pattern analysis,',
    '  not a verified lie detection system.',
    '═══════════════════════════════════════════════',
  ];

  const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `verity-analysis-${Date.now()}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function ResultsPanel({ result, originalText, onReset }: ResultsPanelProps) {
  const [activePattern, setActivePattern] = useState<PatternFlag | null>(null);

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="flex flex-col gap-4 h-full"
    >
      {/* Top: Gauge + Breakdown side by side */}
      <div className="grid grid-cols-1 lg:grid-cols-[auto_1fr] gap-4">
        {/* Gauge */}
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.5 }}
          className="panel p-6 flex flex-col items-center justify-center"
        >
          <div className="font-mono text-[10px] text-[#3D5166] tracking-widest mb-4">DECEPTION SCORE</div>
          <DeceptionGauge
            score={result.deceptionScore}
            verdict={result.verdict}
            confidence={result.confidence}
            animated
          />

          {/* Action buttons */}
          <div className="flex items-center gap-2 mt-4">
            <button
              onClick={onReset}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded border border-[#1A2840] hover:border-[#243652] text-[#3D5166] hover:text-[#7A8FA6] font-mono text-[10px] tracking-wider transition-all"
            >
              <RotateCcw size={11} />
              NEW
            </button>
            <button
              onClick={() => exportReport(result, originalText)}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded border border-[#1A2840] hover:border-[#243652] text-[#3D5166] hover:text-[#7A8FA6] font-mono text-[10px] tracking-wider transition-all"
            >
              <Download size={11} />
              EXPORT
            </button>
          </div>
        </motion.div>

        {/* Breakdown */}
        <motion.div
          initial={{ opacity: 0, x: 10 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: 0.15, duration: 0.4 }}
          className="panel p-4 overflow-y-auto max-h-[480px]"
        >
          <BreakdownPanel
            result={result}
            activePattern={activePattern}
            onPatternSelect={setActivePattern}
          />
        </motion.div>
      </div>

      {/* Highlighted text */}
      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.3, duration: 0.4 }}
        className="panel p-4"
      >
        <div className="font-mono text-[10px] text-[#3D5166] tracking-widest mb-3 flex items-center gap-2">
          <div className="h-px flex-1 bg-[#1A2840]" />
          ANNOTATED TEXT — HOVER HIGHLIGHTS FOR DETAILS
          <div className="h-px flex-1 bg-[#1A2840]" />
        </div>
        <PatternHighlighter
          text={originalText}
          patterns={result.patterns}
          onPatternClick={setActivePattern}
        />
      </motion.div>

      {/* Disclaimer */}
      <p className="text-center font-mono text-[9px] text-[#3D5166] tracking-wider pb-2">
        VERITY analyzes linguistic patterns only — not a verified lie detection system. Results are probabilistic.
      </p>
    </motion.div>
  );
}
